services:
  # nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/public:/var/www/html/public
    depends_on:
      - server

  # php
  server:
    build:
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server/public:/var/www/html/public
      - ./server:/var/www/html
    env_file:
      - ./server/.env

  # mysql
  database:
    image: mysql:lts
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  # redis

volumes:
  mysqldata:
